2022-05-09 11:12:14 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Scalar subquery contains more than one row; SQL statement:
SELECT SELECT P.PAYMENT_ID, P.AMOUNT, E.NAME 
                                            FROM EMPLOYEE E 
                                            INNER JOIN PAYMENT P ON (E.EMPLOYEE_ID = P.EMPLOYEE_ID)
                                            ORDER BY p.PAYMENT_ID asc [90053-212]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:646)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.expression.Subquery.getValue(Subquery.java:53)
	at org.h2.command.query.Select$LazyResultQueryFlat.fetchNextRow(Select.java:1830)
	at org.h2.result.LazyResult.hasNext(LazyResult.java:78)
	at org.h2.result.FetchedResult.next(FetchedResult.java:34)
	at org.h2.command.query.Select.queryFlat(Select.java:728)
	at org.h2.command.query.Select.queryWithoutCache(Select.java:833)
	at org.h2.command.query.Query.queryWithoutCacheLazyCheck(Query.java:197)
	at org.h2.command.query.Query.query(Query.java:512)
	at org.h2.command.query.Query.query(Query.java:475)
	at org.h2.command.CommandContainer.query(CommandContainer.java:256)
	at org.h2.command.Command.executeQuery(Command.java:190)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:247)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:223)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1339)
	at org.h2.server.web.WebApp.query(WebApp.java:1137)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1103)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1090)
	at org.h2.server.web.WebThread.process(WebThread.java:189)
	at org.h2.server.web.WebThread.run(WebThread.java:102)
	at java.lang.Thread.run(Thread.java:748)
2022-05-09 11:41:51 database: flush
org.h2.message.DbException: General error: "org.h2.mvstore.MVStoreException: The file is locked: /Users/marcio.mnz/repos/ballerina-wso2-hackathon-project-templates/problem_2_4/db/so2wdb.mv.db [2.0.206/7]" [50000-206]
	at org.h2.message.DbException.get(DbException.java:216)
	at org.h2.message.DbException.convert(DbException.java:414)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:120)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:3292)
	at org.h2.mvstore.MVStore.panic(MVStore.java:585)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:461)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:4052)
	at org.h2.mvstore.db.Store.<init>(Store.java:129)
	at org.h2.engine.Database.<init>(Database.java:324)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:117)
	at org.h2.Driver.connect(Driver.java:59)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:353)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:562)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at io.ballerina.stdlib.sql.datasource.SQLDatasource.buildNonXADataSource(SQLDatasource.java:353)
	at io.ballerina.stdlib.sql.datasource.SQLDatasource.<init>(SQLDatasource.java:82)
	at io.ballerina.stdlib.sql.datasource.SQLDatasource.createAndInitDatasource(SQLDatasource.java:233)
	at io.ballerina.stdlib.sql.datasource.SQLDatasource.lambda$retrieveDatasource$1(SQLDatasource.java:152)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at io.ballerina.stdlib.sql.datasource.SQLDatasource.retrieveDatasource(SQLDatasource.java:151)
	at io.ballerina.stdlib.sql.nativeimpl.ClientProcessor.createClient(ClientProcessor.java:64)
	at io.ballerina.stdlib.java.jdbc.nativeimpl.ClientProcessor.createClient(ClientProcessor.java:98)
	at ballerinax.java$0046jdbc.1.client.createClient(client.bal:148)
	at ballerinax.java$0046jdbc.1.$value$Client.init(client.bal:43)
	at ballerinax.java$0046jdbc.1.$value$Client.call(client.bal)
	at ballerinax.java$0046jdbc.1.$value$Client.$init$(client.bal:35)
	at ballerinax.java$0046jdbc.1.$value$Client.call(client.bal)
	at balHack.problem_2_4.0.main.getHighPaymentDetails(main.bal:15)
	at balHack.problem_2_4.0.tests.tests.getHighValuesTest(tests/tests.bal:7)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.lambda$runOnSchedule$0(TesterinaFunction.java:108)
	at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:610)
	at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:316)
	at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:283)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "org.h2.mvstore.MVStoreException: The file is locked: /Users/marcio.mnz/repos/ballerina-wso2-hackathon-project-templates/problem_2_4/db/so2wdb.mv.db [2.0.206/7]" [50000-206]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:573)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:496)
	... 46 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: /Users/marcio.mnz/repos/ballerina-wso2-hackathon-project-templates/problem_2_4/db/so2wdb.mv.db [2.0.206/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:1004)
	at org.h2.mvstore.FileStore.open(FileStore.java:163)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:444)
	... 40 more
2022-05-09 11:43:22 database: flush
org.h2.message.DbException: General error: "org.h2.mvstore.MVStoreException: The file is locked: /Users/marcio.mnz/repos/ballerina-wso2-hackathon-project-templates/problem_2_4/db/so2wdb.mv.db [2.0.206/7]" [50000-206]
	at org.h2.message.DbException.get(DbException.java:216)
	at org.h2.message.DbException.convert(DbException.java:414)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:120)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:3292)
	at org.h2.mvstore.MVStore.panic(MVStore.java:585)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:461)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:4052)
	at org.h2.mvstore.db.Store.<init>(Store.java:129)
	at org.h2.engine.Database.<init>(Database.java:324)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:117)
	at org.h2.Driver.connect(Driver.java:59)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:353)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:562)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at io.ballerina.stdlib.sql.datasource.SQLDatasource.buildNonXADataSource(SQLDatasource.java:353)
	at io.ballerina.stdlib.sql.datasource.SQLDatasource.<init>(SQLDatasource.java:82)
	at io.ballerina.stdlib.sql.datasource.SQLDatasource.createAndInitDatasource(SQLDatasource.java:233)
	at io.ballerina.stdlib.sql.datasource.SQLDatasource.lambda$retrieveDatasource$1(SQLDatasource.java:152)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at io.ballerina.stdlib.sql.datasource.SQLDatasource.retrieveDatasource(SQLDatasource.java:151)
	at io.ballerina.stdlib.sql.nativeimpl.ClientProcessor.createClient(ClientProcessor.java:64)
	at io.ballerina.stdlib.java.jdbc.nativeimpl.ClientProcessor.createClient(ClientProcessor.java:98)
	at ballerinax.java$0046jdbc.1.client.createClient(client.bal:148)
	at ballerinax.java$0046jdbc.1.$value$Client.init(client.bal:43)
	at ballerinax.java$0046jdbc.1.$value$Client.call(client.bal)
	at ballerinax.java$0046jdbc.1.$value$Client.$init$(client.bal:35)
	at ballerinax.java$0046jdbc.1.$value$Client.call(client.bal)
	at balHack.problem_2_4.0.main.getHighPaymentDetails(main.bal:15)
	at balHack.problem_2_4.0.tests.tests.getHighValuesTest(tests/tests.bal:7)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.lambda$runOnSchedule$0(TesterinaFunction.java:108)
	at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:610)
	at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:316)
	at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:283)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "org.h2.mvstore.MVStoreException: The file is locked: /Users/marcio.mnz/repos/ballerina-wso2-hackathon-project-templates/problem_2_4/db/so2wdb.mv.db [2.0.206/7]" [50000-206]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:573)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:496)
	... 46 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: /Users/marcio.mnz/repos/ballerina-wso2-hackathon-project-templates/problem_2_4/db/so2wdb.mv.db [2.0.206/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:1004)
	at org.h2.mvstore.FileStore.open(FileStore.java:163)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:444)
	... 40 more
2022-05-09 11:44:25 database: flush
org.h2.message.DbException: General error: "org.h2.mvstore.MVStoreException: The file is locked: /Users/marcio.mnz/repos/ballerina-wso2-hackathon-project-templates/problem_2_4/db/so2wdb.mv.db [2.0.206/7]" [50000-206]
	at org.h2.message.DbException.get(DbException.java:216)
	at org.h2.message.DbException.convert(DbException.java:414)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:120)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:3292)
	at org.h2.mvstore.MVStore.panic(MVStore.java:585)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:461)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:4052)
	at org.h2.mvstore.db.Store.<init>(Store.java:129)
	at org.h2.engine.Database.<init>(Database.java:324)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:117)
	at org.h2.Driver.connect(Driver.java:59)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:353)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:562)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at io.ballerina.stdlib.sql.datasource.SQLDatasource.buildNonXADataSource(SQLDatasource.java:353)
	at io.ballerina.stdlib.sql.datasource.SQLDatasource.<init>(SQLDatasource.java:82)
	at io.ballerina.stdlib.sql.datasource.SQLDatasource.createAndInitDatasource(SQLDatasource.java:233)
	at io.ballerina.stdlib.sql.datasource.SQLDatasource.lambda$retrieveDatasource$1(SQLDatasource.java:152)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at io.ballerina.stdlib.sql.datasource.SQLDatasource.retrieveDatasource(SQLDatasource.java:151)
	at io.ballerina.stdlib.sql.nativeimpl.ClientProcessor.createClient(ClientProcessor.java:64)
	at io.ballerina.stdlib.java.jdbc.nativeimpl.ClientProcessor.createClient(ClientProcessor.java:98)
	at ballerinax.java$0046jdbc.1.client.createClient(client.bal:148)
	at ballerinax.java$0046jdbc.1.$value$Client.init(client.bal:43)
	at ballerinax.java$0046jdbc.1.$value$Client.call(client.bal)
	at ballerinax.java$0046jdbc.1.$value$Client.$init$(client.bal:35)
	at ballerinax.java$0046jdbc.1.$value$Client.call(client.bal)
	at balHack.problem_2_4.0.main.getHighPaymentDetails(main.bal:15)
	at balHack.problem_2_4.0.tests.tests.getHighValuesTest(tests/tests.bal:7)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.lambda$runOnSchedule$0(TesterinaFunction.java:108)
	at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:610)
	at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:316)
	at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:283)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "org.h2.mvstore.MVStoreException: The file is locked: /Users/marcio.mnz/repos/ballerina-wso2-hackathon-project-templates/problem_2_4/db/so2wdb.mv.db [2.0.206/7]" [50000-206]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:573)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:496)
	... 46 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: /Users/marcio.mnz/repos/ballerina-wso2-hackathon-project-templates/problem_2_4/db/so2wdb.mv.db [2.0.206/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:1004)
	at org.h2.mvstore.FileStore.open(FileStore.java:163)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:444)
	... 40 more
2022-05-09 11:45:14 database: flush
org.h2.message.DbException: General error: "org.h2.mvstore.MVStoreException: The file is locked: /Users/marcio.mnz/repos/ballerina-wso2-hackathon-project-templates/problem_2_4/db/so2wdb.mv.db [2.0.206/7]" [50000-206]
	at org.h2.message.DbException.get(DbException.java:216)
	at org.h2.message.DbException.convert(DbException.java:414)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:120)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:3292)
	at org.h2.mvstore.MVStore.panic(MVStore.java:585)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:461)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:4052)
	at org.h2.mvstore.db.Store.<init>(Store.java:129)
	at org.h2.engine.Database.<init>(Database.java:324)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:117)
	at org.h2.Driver.connect(Driver.java:59)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:353)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:562)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at io.ballerina.stdlib.sql.datasource.SQLDatasource.buildNonXADataSource(SQLDatasource.java:353)
	at io.ballerina.stdlib.sql.datasource.SQLDatasource.<init>(SQLDatasource.java:82)
	at io.ballerina.stdlib.sql.datasource.SQLDatasource.createAndInitDatasource(SQLDatasource.java:233)
	at io.ballerina.stdlib.sql.datasource.SQLDatasource.lambda$retrieveDatasource$1(SQLDatasource.java:152)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at io.ballerina.stdlib.sql.datasource.SQLDatasource.retrieveDatasource(SQLDatasource.java:151)
	at io.ballerina.stdlib.sql.nativeimpl.ClientProcessor.createClient(ClientProcessor.java:64)
	at io.ballerina.stdlib.java.jdbc.nativeimpl.ClientProcessor.createClient(ClientProcessor.java:98)
	at ballerinax.java$0046jdbc.1.client.createClient(client.bal:148)
	at ballerinax.java$0046jdbc.1.$value$Client.init(client.bal:43)
	at ballerinax.java$0046jdbc.1.$value$Client.call(client.bal)
	at ballerinax.java$0046jdbc.1.$value$Client.$init$(client.bal:35)
	at ballerinax.java$0046jdbc.1.$value$Client.call(client.bal)
	at balHack.problem_2_4.0.main.getHighPaymentDetails(main.bal:16)
	at balHack.problem_2_4.0.tests.tests.getHighValuesTest(tests/tests.bal:7)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.lambda$runOnSchedule$0(TesterinaFunction.java:108)
	at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:610)
	at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:316)
	at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:283)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "org.h2.mvstore.MVStoreException: The file is locked: /Users/marcio.mnz/repos/ballerina-wso2-hackathon-project-templates/problem_2_4/db/so2wdb.mv.db [2.0.206/7]" [50000-206]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:573)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:496)
	... 46 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: /Users/marcio.mnz/repos/ballerina-wso2-hackathon-project-templates/problem_2_4/db/so2wdb.mv.db [2.0.206/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:1004)
	at org.h2.mvstore.FileStore.open(FileStore.java:163)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:444)
	... 40 more
2022-05-09 11:46:51 database: flush
org.h2.message.DbException: General error: "org.h2.mvstore.MVStoreException: The file is locked: /Users/marcio.mnz/repos/ballerina-wso2-hackathon-project-templates/problem_2_4/db/so2wdb.mv.db [2.0.206/7]" [50000-206]
	at org.h2.message.DbException.get(DbException.java:216)
	at org.h2.message.DbException.convert(DbException.java:414)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:120)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:3292)
	at org.h2.mvstore.MVStore.panic(MVStore.java:585)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:461)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:4052)
	at org.h2.mvstore.db.Store.<init>(Store.java:129)
	at org.h2.engine.Database.<init>(Database.java:324)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:117)
	at org.h2.Driver.connect(Driver.java:59)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:353)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:562)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at io.ballerina.stdlib.sql.datasource.SQLDatasource.buildNonXADataSource(SQLDatasource.java:353)
	at io.ballerina.stdlib.sql.datasource.SQLDatasource.<init>(SQLDatasource.java:82)
	at io.ballerina.stdlib.sql.datasource.SQLDatasource.createAndInitDatasource(SQLDatasource.java:233)
	at io.ballerina.stdlib.sql.datasource.SQLDatasource.lambda$retrieveDatasource$1(SQLDatasource.java:152)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at io.ballerina.stdlib.sql.datasource.SQLDatasource.retrieveDatasource(SQLDatasource.java:151)
	at io.ballerina.stdlib.sql.nativeimpl.ClientProcessor.createClient(ClientProcessor.java:64)
	at io.ballerina.stdlib.java.jdbc.nativeimpl.ClientProcessor.createClient(ClientProcessor.java:98)
	at ballerinax.java$0046jdbc.1.client.createClient(client.bal:148)
	at ballerinax.java$0046jdbc.1.$value$Client.init(client.bal:43)
	at ballerinax.java$0046jdbc.1.$value$Client.call(client.bal)
	at ballerinax.java$0046jdbc.1.$value$Client.$init$(client.bal:35)
	at ballerinax.java$0046jdbc.1.$value$Client.call(client.bal)
	at balHack.problem_2_4.0.main.getHighPaymentDetails(main.bal:16)
	at balHack.problem_2_4.0.tests.tests.getHighValuesTest(tests/tests.bal:7)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.lambda$runOnSchedule$0(TesterinaFunction.java:108)
	at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:610)
	at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:316)
	at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:283)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "org.h2.mvstore.MVStoreException: The file is locked: /Users/marcio.mnz/repos/ballerina-wso2-hackathon-project-templates/problem_2_4/db/so2wdb.mv.db [2.0.206/7]" [50000-206]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:573)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:496)
	... 46 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: /Users/marcio.mnz/repos/ballerina-wso2-hackathon-project-templates/problem_2_4/db/so2wdb.mv.db [2.0.206/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:1004)
	at org.h2.mvstore.FileStore.open(FileStore.java:163)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:444)
	... 40 more
2022-05-09 11:47:36 database: flush
org.h2.message.DbException: General error: "org.h2.mvstore.MVStoreException: The file is locked: /Users/marcio.mnz/repos/ballerina-wso2-hackathon-project-templates/problem_2_4/db/so2wdb.mv.db [2.0.206/7]" [50000-206]
	at org.h2.message.DbException.get(DbException.java:216)
	at org.h2.message.DbException.convert(DbException.java:414)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:120)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:3292)
	at org.h2.mvstore.MVStore.panic(MVStore.java:585)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:461)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:4052)
	at org.h2.mvstore.db.Store.<init>(Store.java:129)
	at org.h2.engine.Database.<init>(Database.java:324)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:117)
	at org.h2.Driver.connect(Driver.java:59)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:353)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:562)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at io.ballerina.stdlib.sql.datasource.SQLDatasource.buildNonXADataSource(SQLDatasource.java:353)
	at io.ballerina.stdlib.sql.datasource.SQLDatasource.<init>(SQLDatasource.java:82)
	at io.ballerina.stdlib.sql.datasource.SQLDatasource.createAndInitDatasource(SQLDatasource.java:233)
	at io.ballerina.stdlib.sql.datasource.SQLDatasource.lambda$retrieveDatasource$1(SQLDatasource.java:152)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at io.ballerina.stdlib.sql.datasource.SQLDatasource.retrieveDatasource(SQLDatasource.java:151)
	at io.ballerina.stdlib.sql.nativeimpl.ClientProcessor.createClient(ClientProcessor.java:64)
	at io.ballerina.stdlib.java.jdbc.nativeimpl.ClientProcessor.createClient(ClientProcessor.java:98)
	at ballerinax.java$0046jdbc.1.client.createClient(client.bal:148)
	at ballerinax.java$0046jdbc.1.$value$Client.init(client.bal:43)
	at ballerinax.java$0046jdbc.1.$value$Client.call(client.bal)
	at ballerinax.java$0046jdbc.1.$value$Client.$init$(client.bal:35)
	at ballerinax.java$0046jdbc.1.$value$Client.call(client.bal)
	at balHack.problem_2_4.0.main.getHighPaymentDetails(main.bal:16)
	at balHack.problem_2_4.0.tests.tests.getHighValuesTest(tests/tests.bal:7)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.lambda$runOnSchedule$0(TesterinaFunction.java:108)
	at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:610)
	at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:316)
	at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:283)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "org.h2.mvstore.MVStoreException: The file is locked: /Users/marcio.mnz/repos/ballerina-wso2-hackathon-project-templates/problem_2_4/db/so2wdb.mv.db [2.0.206/7]" [50000-206]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:573)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:496)
	... 46 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: /Users/marcio.mnz/repos/ballerina-wso2-hackathon-project-templates/problem_2_4/db/so2wdb.mv.db [2.0.206/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:1004)
	at org.h2.mvstore.FileStore.open(FileStore.java:163)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:444)
	... 40 more
2022-05-09 11:48:21 database: flush
org.h2.message.DbException: General error: "org.h2.mvstore.MVStoreException: The file is locked: /Users/marcio.mnz/repos/ballerina-wso2-hackathon-project-templates/problem_2_4/db/so2wdb.mv.db [2.0.206/7]" [50000-206]
	at org.h2.message.DbException.get(DbException.java:216)
	at org.h2.message.DbException.convert(DbException.java:414)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:120)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:3292)
	at org.h2.mvstore.MVStore.panic(MVStore.java:585)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:461)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:4052)
	at org.h2.mvstore.db.Store.<init>(Store.java:129)
	at org.h2.engine.Database.<init>(Database.java:324)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:117)
	at org.h2.Driver.connect(Driver.java:59)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:353)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:562)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at io.ballerina.stdlib.sql.datasource.SQLDatasource.buildNonXADataSource(SQLDatasource.java:353)
	at io.ballerina.stdlib.sql.datasource.SQLDatasource.<init>(SQLDatasource.java:82)
	at io.ballerina.stdlib.sql.datasource.SQLDatasource.createAndInitDatasource(SQLDatasource.java:233)
	at io.ballerina.stdlib.sql.datasource.SQLDatasource.lambda$retrieveDatasource$1(SQLDatasource.java:152)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at io.ballerina.stdlib.sql.datasource.SQLDatasource.retrieveDatasource(SQLDatasource.java:151)
	at io.ballerina.stdlib.sql.nativeimpl.ClientProcessor.createClient(ClientProcessor.java:64)
	at io.ballerina.stdlib.java.jdbc.nativeimpl.ClientProcessor.createClient(ClientProcessor.java:98)
	at ballerinax.java$0046jdbc.1.client.createClient(client.bal:148)
	at ballerinax.java$0046jdbc.1.$value$Client.init(client.bal:43)
	at ballerinax.java$0046jdbc.1.$value$Client.call(client.bal)
	at ballerinax.java$0046jdbc.1.$value$Client.$init$(client.bal:35)
	at ballerinax.java$0046jdbc.1.$value$Client.call(client.bal)
	at balHack.problem_2_4.0.main.getHighPaymentDetails(main.bal:16)
	at balHack.problem_2_4.0.tests.tests.getHighValuesTest(tests/tests.bal:7)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.lambda$runOnSchedule$0(TesterinaFunction.java:108)
	at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:610)
	at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:316)
	at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:283)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "org.h2.mvstore.MVStoreException: The file is locked: /Users/marcio.mnz/repos/ballerina-wso2-hackathon-project-templates/problem_2_4/db/so2wdb.mv.db [2.0.206/7]" [50000-206]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:573)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:496)
	... 46 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: /Users/marcio.mnz/repos/ballerina-wso2-hackathon-project-templates/problem_2_4/db/so2wdb.mv.db [2.0.206/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:1004)
	at org.h2.mvstore.FileStore.open(FileStore.java:163)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:444)
	... 40 more
2022-05-09 11:48:52 database: flush
org.h2.message.DbException: General error: "org.h2.mvstore.MVStoreException: The file is locked: /Users/marcio.mnz/repos/ballerina-wso2-hackathon-project-templates/problem_2_4/db/so2wdb.mv.db [2.0.206/7]" [50000-206]
	at org.h2.message.DbException.get(DbException.java:216)
	at org.h2.message.DbException.convert(DbException.java:414)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:120)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:3292)
	at org.h2.mvstore.MVStore.panic(MVStore.java:585)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:461)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:4052)
	at org.h2.mvstore.db.Store.<init>(Store.java:129)
	at org.h2.engine.Database.<init>(Database.java:324)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:117)
	at org.h2.Driver.connect(Driver.java:59)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:353)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:562)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at io.ballerina.stdlib.sql.datasource.SQLDatasource.buildNonXADataSource(SQLDatasource.java:353)
	at io.ballerina.stdlib.sql.datasource.SQLDatasource.<init>(SQLDatasource.java:82)
	at io.ballerina.stdlib.sql.datasource.SQLDatasource.createAndInitDatasource(SQLDatasource.java:233)
	at io.ballerina.stdlib.sql.datasource.SQLDatasource.lambda$retrieveDatasource$1(SQLDatasource.java:152)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at io.ballerina.stdlib.sql.datasource.SQLDatasource.retrieveDatasource(SQLDatasource.java:151)
	at io.ballerina.stdlib.sql.nativeimpl.ClientProcessor.createClient(ClientProcessor.java:64)
	at io.ballerina.stdlib.java.jdbc.nativeimpl.ClientProcessor.createClient(ClientProcessor.java:98)
	at ballerinax.java$0046jdbc.1.client.createClient(client.bal:148)
	at ballerinax.java$0046jdbc.1.$value$Client.init(client.bal:43)
	at ballerinax.java$0046jdbc.1.$value$Client.call(client.bal)
	at ballerinax.java$0046jdbc.1.$value$Client.$init$(client.bal:35)
	at ballerinax.java$0046jdbc.1.$value$Client.call(client.bal)
	at balHack.problem_2_4.0.main.getHighPaymentDetails(main.bal:16)
	at balHack.problem_2_4.0.tests.tests.getHighValuesTest(tests/tests.bal:7)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.lambda$runOnSchedule$0(TesterinaFunction.java:108)
	at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:610)
	at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:316)
	at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:283)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "org.h2.mvstore.MVStoreException: The file is locked: /Users/marcio.mnz/repos/ballerina-wso2-hackathon-project-templates/problem_2_4/db/so2wdb.mv.db [2.0.206/7]" [50000-206]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:573)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:496)
	... 46 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: /Users/marcio.mnz/repos/ballerina-wso2-hackathon-project-templates/problem_2_4/db/so2wdb.mv.db [2.0.206/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:1004)
	at org.h2.mvstore.FileStore.open(FileStore.java:163)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:444)
	... 40 more
2022-06-02 15:08:18 database: wrong user or password; user: ""
org.h2.message.DbException: Wrong user name or password [28000-206]
	at org.h2.message.DbException.get(DbException.java:227)
	at org.h2.message.DbException.get(DbException.java:203)
	at org.h2.message.DbException.get(DbException.java:192)
	at org.h2.engine.Engine.openSession(Engine.java:154)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:117)
	at org.h2.Driver.connect(Driver.java:59)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:353)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:562)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at io.ballerina.stdlib.sql.datasource.SQLDatasource.buildNonXADataSource(SQLDatasource.java:353)
	at io.ballerina.stdlib.sql.datasource.SQLDatasource.<init>(SQLDatasource.java:82)
	at io.ballerina.stdlib.sql.datasource.SQLDatasource.createAndInitDatasource(SQLDatasource.java:233)
	at io.ballerina.stdlib.sql.datasource.SQLDatasource.lambda$retrieveDatasource$1(SQLDatasource.java:152)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at io.ballerina.stdlib.sql.datasource.SQLDatasource.retrieveDatasource(SQLDatasource.java:151)
	at io.ballerina.stdlib.sql.nativeimpl.ClientProcessor.createClient(ClientProcessor.java:64)
	at io.ballerina.stdlib.java.jdbc.nativeimpl.ClientProcessor.createClient(ClientProcessor.java:98)
	at ballerinax.java$0046jdbc.1.client.createClient(client.bal:148)
	at ballerinax.java$0046jdbc.1.$value$Client.init(client.bal:43)
	at ballerinax.java$0046jdbc.1.$value$Client.call(client.bal)
	at ballerinax.java$0046jdbc.1.$value$Client.$init$(client.bal:35)
	at ballerinax.java$0046jdbc.1.$value$Client.call(client.bal)
	at marciowso2.dataops_simplified_with_ballerina.0.main.getHighPaymentDetails(main.bal:15)
	at marciowso2.dataops_simplified_with_ballerina.0.tests.tests.getHighValuesTest(tests/tests.bal:7)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.lambda$runOnSchedule$0(TesterinaFunction.java:108)
	at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:610)
	at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:316)
	at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:283)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.h2.jdbc.JdbcSQLInvalidAuthorizationSpecException: Wrong user name or password [28000-206]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:529)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:496)
	... 40 more
2022-06-02 15:14:33 database: wrong user or password; user: ""
org.h2.message.DbException: Wrong user name or password [28000-206]
	at org.h2.message.DbException.get(DbException.java:227)
	at org.h2.message.DbException.get(DbException.java:203)
	at org.h2.message.DbException.get(DbException.java:192)
	at org.h2.engine.Engine.openSession(Engine.java:154)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:117)
	at org.h2.Driver.connect(Driver.java:59)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:353)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:562)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at io.ballerina.stdlib.sql.datasource.SQLDatasource.buildNonXADataSource(SQLDatasource.java:353)
	at io.ballerina.stdlib.sql.datasource.SQLDatasource.<init>(SQLDatasource.java:82)
	at io.ballerina.stdlib.sql.datasource.SQLDatasource.createAndInitDatasource(SQLDatasource.java:233)
	at io.ballerina.stdlib.sql.datasource.SQLDatasource.lambda$retrieveDatasource$1(SQLDatasource.java:152)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at io.ballerina.stdlib.sql.datasource.SQLDatasource.retrieveDatasource(SQLDatasource.java:151)
	at io.ballerina.stdlib.sql.nativeimpl.ClientProcessor.createClient(ClientProcessor.java:64)
	at io.ballerina.stdlib.java.jdbc.nativeimpl.ClientProcessor.createClient(ClientProcessor.java:98)
	at ballerinax.java$0046jdbc.1.client.createClient(client.bal:148)
	at ballerinax.java$0046jdbc.1.$value$Client.init(client.bal:43)
	at ballerinax.java$0046jdbc.1.$value$Client.call(client.bal)
	at ballerinax.java$0046jdbc.1.$value$Client.$init$(client.bal:35)
	at ballerinax.java$0046jdbc.1.$value$Client.call(client.bal)
	at marciowso2.dataops_simplified_with_ballerina.0.main.getHighPaymentDetails(main.bal:15)
	at marciowso2.dataops_simplified_with_ballerina.0.tests.tests.getHighValuesTest(tests/tests.bal:7)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.lambda$runOnSchedule$0(TesterinaFunction.java:108)
	at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:610)
	at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:316)
	at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:283)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.h2.jdbc.JdbcSQLInvalidAuthorizationSpecException: Wrong user name or password [28000-206]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:529)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:496)
	... 40 more
